[theme]
base = "dark"
primaryColor="#6eb52f"
backgroundColor="#f0f0f5"
secondaryBackgroundColor="#e0e0ef"
textColor="#262730"
font="sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[runner]
fastReruns = true

[logger]
level = "error"